'use strict';
// Review-only fixture. No network, credentials, persistence or production code.
const app=document.querySelector('#app'), device=document.querySelector('.device');
const state={screen:'insight',status:'normal',period:'3M',chart:'candle',point:null,connected:true,remember:false,holdingScroll:0,settingsReturn:'settings',pendingInsight:false,connectionNotice:false};
const backIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 5-7 7 7 7M5 12h15"/></svg>';
const refreshIcon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M20 7v5h-5M4 17v-5h5M19 12a7 7 0 0 0-12-5M5 12a7 7 0 0 0 12 5"/></svg>';
const names={normal:'예시 데이터',disconnected:'미연결',partial:'일부 정보 없음',expired:'연결 만료',offline:'오프라인 · 저장된 예시'};
const sections=['개요','재무','애널리스트','옵션','내부자','뉴스'];
const ids=['overview-section','financial','analysts','options','insiders','news'];
const tradingDates=[];for(let d=new Date('2025-09-05T12:00:00Z');d<=new Date('2026-09-04T12:00:00Z');d.setUTCDate(d.getUTCDate()+1)){if(d.getUTCDay()!==0&&d.getUTCDay()!==6)tradingDates.push(d.toISOString().slice(0,10));}
const points=tradingDates.map((date,i)=>{const end=tradingDates.length-1;const raw=n=>248+n*.27+Math.sin(n*.31)*7+Math.cos(n*.12)*4;const close=+(raw(i)+316.15-raw(end)).toFixed(2),open=+(close+Math.sin(i*1.71)*4).toFixed(2);return {date,open,close,high:+(Math.max(open,close)+3.4).toFixed(2),low:+(Math.min(open,close)-2.8).toFixed(2),volume:Math.round(12000000+(Math.sin(i*.7)+1)*6000000)};});
const metrics=[['시가총액','$1.49T','전일 $1.47T 대비 +1.36%'],['PER · 최근 12개월','62.4배','업종 평균 48.1배'],['EPS · 최근 12개월','$5.13','전년 $4.34 대비 +18.2%'],['분기 매출','$16.8B','2026 회계연도 Q3 · 전년 $14.11B 대비 +19.1%'],['배당수익률','0.78%','전년 0.72% 대비 +0.06%p'],['ROE','24.8%','이전 분기 23.1% 대비 +1.7%p'],['공매도 비중','1.20%','이전 1.10% 대비 +0.10%p'],['상환 소요일','1.8일','이전 1.6일 대비 +0.2일']];
const quarters=[['Q4 ’25','14.1','+17.5%'],['Q1 ’26','14.9','+18.3%'],['Q2 ’26','15.7','+18.9%'],['Q3 ’26','16.8','+19.1%']];
const firms=[['North Research','매수','$380','09.08'],['Harbor Equity','매수','$365','09.06'],['Pine Capital','보유','$330','09.04'],['Cedar Markets','매수','$370','09.03'],['Stone Analytics','매도','$280','09.02'],['Lake Securities','매수','$375','09.01']];
const trades=[['09.04','임원 A','매도','5,000','$318.00'],['08.28','임원 B','매수','1,000','$305.00'],['08.22','임원 C','매도','3,500','$302.00'],['08.15','임원 D','매도','2,000','$295.00']];
function row(label,value,compare=''){return `<div class="row"><span>${label}</span><span><strong>${value}</strong>${compare?`<small>${compare}</small>`:''}</span></div>`}
function rows(data){return `<div class="rows">${data.map(r=>row(...r)).join('')}</div>`}
function table(headers,data){return `<table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${data.map(r=>`<tr>${r.map((v,i)=>i?`<td>${v}</td>`:`<th scope="row">${v}</th>`).join('')}</tr>`).join('')}</tbody></table>`}
function disclosure(title,body){return `<details><summary>${title}</summary><div class="details-body">${body}</div></details>`}
function header(title,refresh=true){return `<header class="topbar"><button class="icon" data-action="back" aria-label="뒤로">${backIcon}</button><h2>${title}</h2>${refresh?`<button class="icon" data-action="refresh" aria-label="예시 데이터 새로고침">${refreshIcon}</button>`:''}</header>`}
function notice(){if(state.status==='normal')return '';const copy={partial:'옵션 정보를 불러오지 못했습니다. 다른 정보는 확인할 수 있습니다.',expired:'연결을 다시 확인해 주세요. 만료된 연결의 정보는 숨깁니다.',offline:'오프라인입니다. 마지막으로 받은 데이터를 표시합니다.'};return `<div class="notice" role="status"><p>${copy[state.status]}</p><button data-action="${state.status==='expired'?'settings':'retry'}">${state.status==='expired'?'연결 다시 확인':'다시 시도'}</button></div>`}
function insight(){if(state.status==='expired'||!state.connected)return `${header('AVGO',false)}<section><h3>${state.status==='expired'?'연결을 다시 확인해 주세요':'종목 인사이트 연결'}</h3><p>${state.status==='expired'?'연결이 만료되어 인사이트 정보를 숨겼습니다.':'SaveTicker에 연결하면 종목 정보를 확인할 수 있습니다.'}</p><button class="primary" data-action="connection-settings">연결 다시 확인</button></section>`;return `${header('AVGO')}<div class="content">${notice()}<div class="hero"><p class="eyebrow">종목 인사이트 · ${names[state.status]}</p><div class="chart-controls"><div class="segmented" aria-label="차트 기간">${['1M','3M','6M','1Y'].map(p=>`<button data-period="${p}" class="${p===state.period?'selected':''}" aria-pressed="${p===state.period}">${p}</button>`).join('')}</div><button data-action="chart-type" aria-label="${state.chart==='candle'?'라인':'캔들'} 차트로 변경">${state.chart==='candle'?'라인':'캔들'}</button></div><div id="price-chart" class="chart"></div><div class="inspect"><div class="inspect-heading"><div><span class="inspect-label">선택 일봉</span><strong id="selected-date"></strong></div><div class="point-controls"><button data-action="previous-point" aria-label="이전 가격 데이터">‹</button><button data-action="next-point" aria-label="다음 가격 데이터">›</button></div></div><output id="chart-value" aria-live="polite"></output></div><p class="price" style="margin-top:18px">$320.40<small>USD</small></p><p class="change positive">+4.25 (+1.34%) <span class="fine">전일 종가 $316.15 대비</span></p><div class="identity"><strong>브로드컴</strong><p class="fine">Broadcom Inc. · NASDAQ: AVGO</p><p class="fine">반도체 · USD</p></div></div><nav class="anchors" aria-label="인사이트 섹션">${sections.map((s,i)=>`<button data-anchor="${ids[i]}" class="${i===0?'active':''}" aria-label="${s}">${s==='애널리스트'?'애널':s}</button>`).join('')}</nav>
<section id="overview-section"><h3>개요</h3>${rows(metrics)}${disclosure("가격 범위와 거래 현황",rows([["당일 범위","$315.20–$322.80","정규장 종료"],["52주 범위","$188.20–$345.80"],["거래대금","$5.35B","미국 시장 8위 · 예시"],["시가총액 순위","미국 시장 7위"],["시간외 현재가","$321.10","정규장 대비 +0.22%"]]))}</section>
<section id="financial"><h3>재무</h3><p>매출 <strong>$16.8B</strong> <span class="positive">+19.1% YoY</span></p><div class="bars" role="img" aria-label="분기 매출 14.1, 14.9, 15.7, 16.8 십억 달러. 아래 표에서 매출과 전년 대비 증가율 확인">${quarters.map(q=>`<div class="bar-group"><i style="height:${Number(q[1])/18*100}%"></i><span>${q[0]}</span></div>`).join('')}</div><div class="legend"><span>매출 · $B</span></div>${disclosure('전체 분기 수치 · 4개',table(['분기','매출 $B','전년 대비'],quarters))}</section>
<section id="analysts"><h3>애널리스트</h3><p><strong>매수 우세</strong> <span class="fine">리서치 6곳의 예시 의견</span></p><div class="stack" role="img" aria-label="매수 4곳, 보유 1곳, 매도 1곳"><span style="width:66.67%"></span><span class="teal" style="width:16.67%"></span><span class="red" style="width:16.66%"></span></div><div class="legend"><span>매수 4</span><span class="teal">보유 1</span><span class="red">매도 1</span></div>${row('평균 목표가','$350.00','현재가 대비 +9.24%')}<div class="range" role="img" aria-label="목표가 최저 280달러 평균 350달러 최고 380달러. 현재가 320.40달러"><span class="current-price" aria-hidden="true">◇</span></div><p class="fine">◇ 현재가 $320.40 · ● 평균 목표가 $350</p><div class="range-labels"><span>최저 $280</span><span>평균 $350</span><span>최고 $380</span></div>${disclosure('전체 리서치 의견 · 6개',`<p class="fine">기관 이름과 수치는 가상의 예시입니다.</p>${firms.map((f,i)=>`<article class=record><h4>${f[0]} <span class=fine>09.${f[3].slice(3)}</span></h4>${rows([['투자의견',f[1],'이전 '+f[1]],['목표가',f[2],'이전 $'+['360','350','325','350','290','360'][i]],['조정',i===4?'하향':'상향'],['현재가 대비',((Number(f[2].slice(1))/320.4-1)*100).toFixed(2)+'%'],['평가 출처','기관 리포트 · 예시']])}</article>`).join('')}`)}</section>
<section id="options"><h3>옵션</h3>${state.status==='partial'?`<div class="notice" style="margin:16px 0 0"><p>옵션 정보가 없습니다.</p><p class="fine">값이 0이라는 의미가 아닙니다.</p><button data-action="retry">옵션 다시 시도</button></div>`:options()}</section>
<section id="insiders"><h3>내부자 거래</h3><p><strong>기간 집계 · 매수 8건 / 매도 12건</strong></p><p class="negative">순거래 −$4.20M <span class="fine">매수 $2.10M − 매도 $6.30M</span></p><div class="stack" role="img" aria-label="공급자 기간 집계 매수 8건 매도 12건"><span style="width:40%"></span><span class="red" style="width:60%"></span></div><p class="fine">위 수치는 공급자의 30일 집계 예시입니다. 아래 최근 거래 4건은 일부 목록이며 집계의 계산 근거로 사용하지 않습니다.</p>${disclosure('제공된 거래 전체 · 4건',table(['거래일 / 이름','역할 / 유형','금액 $'],trades.map((t,i)=>[`${t[0]}<br>${t[1]}`,`${['CEO','이사','CFO','이사'][i]}<br>${t[2]} (${t[2]==='매수'?'P':'S'})`,['−1,590,000','+305,000','−1,057,000','−590,000'][i]])))}</section>
<section id="news"><h3>뉴스</h3>${[['브로드컴의 분기 실적, 데이터센터 부문 매출 확대','예시 뉴스 · 09.08 14:30 ET'],['반도체 업종 전망과 기업 투자 동향','예시 뉴스 · 09.08 11:10 ET'],['애널리스트, 다음 분기 수익성 추정치 조정','예시 뉴스 · 09.07 16:20 ET']].map(n=>`<button class="news" data-action="news">${n[0]} ↗<span>${n[1]}</span></button>`).join('')}</section>${snapshotFooter()}<div class="footer">디자인 시안 · 모든 수치는 예시 데이터입니다.</div></div>`}
function options(){return `<div class="legend"><span>콜</span><span class="red">풋</span></div>${[['거래량','62','38','12,400','7,600'],['미결제약정','56','44','56,000','44,000'],['프리미엄','68','32','$6.8M','$3.2M']].map(a=>`<div class="row"><span>${a[0]}</span><span>콜 ${a[1]}% / 풋 ${a[2]}%</span></div><div class="stack" role="img" aria-label="${a[0]} 콜 ${a[1]}퍼센트 풋 ${a[2]}퍼센트"><span style="width:${a[1]}%"></span><span class="red" style="width:${a[2]}%"></span></div><p class="fine">콜 ${a[3]} · 풋 ${a[4]} · 제공분 합계 100%</p>`).join('')}<h4>평소와 비교</h4><p class="fine">같은 시각의 평균 거래량 = 100%</p>${[['3일 대비 거래량','142%',142],['7일 대비 거래량','118%',118],['30일 대비 거래량','126%',126]].map(a=>`<div class="row"><span>${a[0]}</span><strong>${a[1]}</strong></div><div style="height:12px;position:relative;background:var(--surface);margin-bottom:16px"><div style="width:${a[2]/2}%;height:100%;background:var(--teal)"></div><span style="position:absolute;left:50%;top:-5px;height:22px;border-left:2px dashed var(--fg)" aria-label="평균 100퍼센트 기준선"></span></div>`).join('')}${rows([['총 옵션 거래량','20,000계약','전체 만기'],['거래량 PCR','0.61','풋 7,600 ÷ 콜 12,400'],['미결제약정 PCR','0.79','풋 44,000 ÷ 콜 56,000'],['만기일','2026.09.18','10일 후 만기'],['맥스페인','$315','가격 수준 · USD'],['콜 월 (Call wall)','$330','가격 수준 · USD'],['풋 월 (Put wall)','$300','가격 수준 · USD'],['감마 전환 가격','$312','가격 수준 · USD'],['기준 주가','$320.40','USD'],['순 감마 노출 (GEX)','+$1.8B','USD · 공급자 정의'],['주가 1% 변화당 감마','+$18.0M','USD / 기초자산 1% 변화']])}<p class="fine">GEX는 가격 수준과 별도 단위로 표시합니다.</p>${disclosure('옵션 원수치 전체',table(['항목','콜','풋'],[['거래량 · 계약','12,400','7,600'],['미결제약정 · 계약','56,000','44,000'],['프리미엄 · USD','6,800,000','3,200,000']]))}`}
function snapshotFooter(){const entries=[
['가격 일봉','2026.09.04 · 16:00','ET · 마지막 완료 봉'],
['현재가 · 가격 범위','2026.09.08 · 16:00','ET · 정규장 종료'],
['시간외 현재가','2026.09.08 · 17:00','ET · 시간외'],
['개요 지표','2026.09.08 · 16:00','ET · 재무 기준 FY2026 Q3'],
['공매도 · 상환 소요일','2026.08.31','결제 기준'],
['분기 매출','FY2026 Q3','최근 회계 분기 · Q4 FY2025–Q3 FY2026'],
['애널리스트','2026.09.08 · 16:00','ET · 각 의견의 평가일은 목록에 표시'],
['옵션 거래량 · 프리미엄','2026.09.08 · 15:45','ET · 잠정 집계'],
['옵션 미결제약정','2026.09.04','전일 스냅샷'],
['옵션 가격 수준 · GEX','2026.09.04','전일 배치 · 거래량과 기준 시점이 다름'],
['내부자 거래','2026.08.10–09.08','보고일 기준 · 최근 30일'],
['뉴스','2026.09.08 · 16:00','ET · 기사의 발행일은 각 기사에 표시']
];return `<section id="data-timestamps" class="timestamps"><div class="timestamp-heading"><span class="timestamp-icon" aria-hidden="true">◷</span><h3>데이터 기준 시점</h3></div><p class="snapshot-intro">SaveTicker · 미국 동부 시간(ET)<br>항목마다 기준 시점이 다릅니다.</p>${state.status==='offline'?'<p class="snapshot-status">오프라인 · 마지막으로 받은 데이터</p>':''}${state.status==='partial'?'<p class="snapshot-status">옵션 조회 실패 · 옵션 기준 시점 확인 불가</p>':''}<div class="timestamp-list">${entries.filter(e=>state.status!=='partial'||!e[0].startsWith('옵션')).map(e=>`<div class="timestamp-row"><span>${e[0]}</span><div><strong>${e[1]}</strong><small>${e[2]}</small></div></div>`).join('')}</div></section>`}
function holding(){return `${header('보유 종목 상세')}<div class="content"><div class="hero"><p class="eyebrow">USA · 예시 계좌</p><h3 class="holding-name">브로드컴</h3><p class="fine">AVGO</p><p class="eyebrow" style="margin-top:28px">평가금액 (USD)</p><p class="price">$3,204.00</p><p class="change positive">평가손익 +$404.00 (+14.43%)</p></div><section><h3>보유 정보</h3>${rows([['보유 수량','10주'],['평균 매입가','$280.00'],['현재가','$320.40'],['매입금액','$2,800.00']])}</section><section class="insight-entry"><button class="insight-link" data-action="insight"><span class="insight-link-copy"><strong>종목 인사이트</strong><br><span class="fine">가격 차트 · 재무 · 시장 분석</span></span><span class="insight-link-arrow" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m9 5 7 7-7 7"/></svg></span></button></section><section><h3>종목 정보</h3>${rows([['시장','NASDAQ'],['통화','USD']])}</section><div class="footer">디자인 시안 · 보유 수량과 계좌는 예시입니다.</div></div>`}
function settings(){return `${header('설정',false)}<div class="content settings-page"><section><h3>화면 모드</h3><p class="section-description">원하는 화면 모드를 선택하세요.</p><div class="theme-options" role="radiogroup" aria-label="화면 모드">${[['dark','다크 모드'],['light','라이트 모드']].map(([mode,label])=>`<button class="theme-option" data-theme-choice="${mode}" role="radio" aria-checked="${device.dataset.theme===mode}"><span class="radio-mark" aria-hidden="true"></span>${label}</button>`).join('')}</div></section><section><h3>연결</h3><button class="settings-link" data-action="connection-settings"><span><strong>SaveTicker</strong><small>종목 인사이트 연결</small></span><span class="settings-link-end"><small>${state.connected?'연결됨':'연결 필요'}</small><span aria-hidden="true">›</span></span></button></section><section><h3>계정</h3><button class="settings-link" data-action="demo-setting"><span>계좌 관리</span><span aria-hidden="true">›</span></button><button class="settings-link" data-action="demo-setting"><span>로그아웃</span><span aria-hidden="true">›</span></button></section><section><h3>앱 정보</h3>${row('현재 버전','1.9.5')}<button class="settings-link" data-action="demo-setting"><span>업데이트 확인</span><span aria-hidden="true">›</span></button></section><div class="footer">디자인 시안 · 설정 변경은 이 미리보기에만 적용됩니다.</div></div>`}
function connection(){return `${header('SaveTicker 연결',false)}<div class="content settings-page connection-page">${state.connectionNotice?'<div class="connection-notice" role="status"><strong>연결 설정이 필요합니다</strong><p>종목 인사이트를 보려면 SaveTicker 계정을 연결해 주세요. 연결하면 선택한 종목으로 돌아갑니다.</p></div>':''}<section><div class="connection-title"><h3>종목 인사이트</h3><span class="connection-status ${state.connected?'is-connected':''}">${state.connected?'연결됨':'미연결'}</span></div><p class="section-description">SaveTicker 계정으로 재무와 시장 분석을 확인합니다.</p>${state.connected?'<div class="connected-account">'+row('연결 계정','demo@example.com')+'</div>':'<div class="connection-form"><label for="demo-id">이메일</label><input id="demo-id" value="demo@example.com" readonly autocomplete="off" aria-describedby="demo-note"><label for="demo-password">비밀번호</label><input id="demo-password" type="password" value="demo-only" readonly autocomplete="off" aria-describedby="demo-note"></div>'}<button class="primary connection-primary" data-action="connect">${state.connected?'연결 다시 확인':'연결하기'}</button><p class="privacy-note">증권사 로그인 정보와 계좌 잔고는 전송하지 않습니다.</p></section><section><h3>연결 정보 저장</h3><div class="switch-row"><span>이 기기에 저장</span><button class="switch" role="switch" aria-label="이 기기에 연결 정보 저장" aria-checked="${state.remember}" data-action="remember"></button></div><p class="storage-help">${storageHelp()}</p></section>${state.connected?'<section><h3>연결 관리</h3><button class="settings-link" data-action="clear-cache"><span>인사이트 캐시 삭제</span><span aria-hidden="true">›</span></button><button class="settings-link negative" data-action="disconnect"><span>연결 해제</span><span aria-hidden="true">›</span></button><p class="section-description">연결을 해제하면 이 연결의 저장 정보도 삭제됩니다.</p></section>':''}<div class="footer" id="demo-note">고정된 예시 계정입니다. 실제 입력·인증·기기 저장은 하지 않습니다.</div></div>`}
function storageHelp(){return state.remember?'기기 화면 잠금이 필요합니다. 보안 저장소에 보호하며 앱 PIN 해제 후 사용합니다. 앱을 벗어나면 잠깁니다.':'앱을 잠그거나 종료하면 연결 정보를 다시 입력합니다.'}
function enterInsight(){if(!state.connected||state.status==='expired'){state.pendingInsight=true;state.connectionNotice=true;state.settingsReturn=state.screen==='connection'?'holding':state.screen;navigate('connection');return}navigate('insight')}
function visiblePoints(){const cutoff=new Date('2026-09-04T12:00:00Z');cutoff.setUTCMonth(cutoff.getUTCMonth()-({'1M':1,'3M':3,'6M':6,'1Y':12}[state.period]));return points.filter(p=>p.date>=cutoff.toISOString().slice(0,10));}
function drawChart(){const target=document.querySelector('#price-chart');if(!target)return;const data=visiblePoints();state.point=Math.max(0,Math.min(state.point??data.length-1,data.length-1));const floor=Math.floor((Math.min(...data.map(d=>d.low))-3)/5)*5,ceiling=Math.ceil((Math.max(...data.map(d=>d.high))+3)/5)*5;const y=v=>150-(v-floor)/(ceiling-floor)*130,x=i=>10+i*(306/(data.length-1));const path=data.map((d,i)=>`${i?'L':'M'}${x(i)},${y(d.close)}`).join(' ');target.innerHTML=`<svg viewBox="0 0 372 216" role="img" aria-label="${state.period} 가격 ${state.chart==='candle'?'캔들':'라인'} 차트. 아래 이전 다음 버튼으로 각 날짜의 시가 고가 저가 종가를 확인하세요.">${[floor,(floor+ceiling)/2,ceiling].map(v=>`<path class="grid" d="M0 ${y(v)}H320"/><text x="328" y="${y(v)+4}">${v}</text>`).join('')}${state.chart==='line'?`<path class="area" d="${path} L316 154 L10 154Z"/><path class="line" d="${path}"/>`:data.map((d,i)=>`<g class="${d.close>=d.open?'up':'down'}"><path d="M${x(i)} ${y(d.high)}V${y(d.low)}"/><rect x="${x(i)-Math.min(3,110/data.length)}" y="${Math.min(y(d.open),y(d.close))}" width="${Math.min(6,220/data.length)}" height="${Math.max(1.6,Math.abs(y(d.open)-y(d.close)))}"/></g>`).join('')}${data.map((d,i)=>`<rect x="${x(i)-1}" y="${190-d.volume/24000000*24}" width="${Math.max(1,220/data.length)}" height="${d.volume/24000000*24}" fill="var(--blue)" opacity=".3"/>`).join('')}<path class="cursor" d="M${x(state.point)} 16V190"/><circle cx="${x(state.point)}" cy="${y(data[state.point].close)}" r="4" fill="var(--blue)"/><text x="0" y="207">${data[0].date.slice(5).replace('-','.')}</text><text x="272" y="207">09.04</text></svg>`;const d=data[state.point];document.querySelector('#selected-date').textContent=d.date.replaceAll("-", ".");document.querySelector('#chart-value').innerHTML=`<dl class="ohlc-grid">${[["시가",d.open],["고가",d.high],["저가",d.low],["종가",d.close]].map(([label,value])=>`<div><dt>${label}</dt><dd>${value.toFixed(2)}</dd></div>`).join("")}</dl><div class="volume-value"><span>거래량</span><strong>${d.volume.toLocaleString("en-US")} <small>주</small></strong></div>`;document.querySelector('[data-action=previous-point]').disabled=state.point===0;document.querySelector('[data-action=next-point]').disabled=state.point===data.length-1;target.onpointerdown=e=>{const rect=target.getBoundingClientRect();state.point=Math.round(Math.max(0,Math.min(1,(e.clientX-rect.left-10*rect.width/372)/(306*rect.width/372)))*(data.length-1));drawChart()};}
function render(){device.querySelector('.anchors')?.remove();app.innerHTML=state.screen==='holding'?holding():state.screen==='settings'?settings():state.screen==='connection'?connection():insight();document.querySelector('#screen').value=state.screen;document.querySelector('#state').value=state.status;const dock=app.querySelector('.anchors');if(dock)device.append(dock);app.classList.toggle('has-dock',Boolean(dock));drawChart();}
function navigate(screen){clearTimeout(toastTimer);document.querySelector('#toast').style.display='none';if(state.screen==='holding')state.holdingScroll=app.scrollTop;state.screen=screen;render();app.scrollTop=screen==='holding'?state.holdingScroll:0;app.querySelector('.topbar h2').setAttribute('tabindex','-1');app.querySelector('.topbar h2').focus({preventScroll:true});}
let toastTimer;function toast(message){const t=document.querySelector('#toast');clearTimeout(toastTimer);t.textContent=message;t.style.display='block';toastTimer=setTimeout(()=>t.style.display='none',3500);}
device.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.themeChoice){device.dataset.theme=b.dataset.themeChoice;document.querySelector('#theme').textContent=device.dataset.theme==='dark'?'라이트 모드 보기':'다크 모드 보기';render();return}if(b.dataset.period){state.period=b.dataset.period;state.point=null;app.querySelectorAll('[data-period]').forEach(x=>{const selected=x.dataset.period===state.period;x.classList.toggle('selected',selected);x.setAttribute('aria-pressed',selected)});drawChart();return}if(b.dataset.anchor){const section=document.getElementById(b.dataset.anchor);section.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});device.querySelectorAll('[data-anchor]').forEach(x=>x.classList.toggle('active',x===b));return}switch(b.dataset.action){case'insight':enterInsight();break;case'connection-settings':state.settingsReturn=state.screen;state.pendingInsight=state.screen==='insight';state.connectionNotice=state.pendingInsight;navigate('connection');break;case'back':{const destination=state.screen==='connection'?state.settingsReturn:'holding';state.pendingInsight=false;state.connectionNotice=false;navigate(destination);break;}case'chart-type':state.chart=state.chart==='candle'?'line':'candle';b.textContent=state.chart==='candle'?'라인':'캔들';b.setAttribute('aria-label',`${b.textContent} 차트로 변경`);drawChart();break;case'previous-point':state.point--;drawChart();break;case'next-point':state.point++;drawChart();break;case'refresh':case'retry':toast(state.status==='normal'?'예시 데이터입니다. 실제 조회는 실행하지 않습니다.':'현재 상태를 유지합니다. 검토 도구에서 정상 상태로 바꿀 수 있습니다.');break;case'news':toast('기사 열기 동작 예시입니다. 외부 페이지로 이동하지 않습니다.');break;case'remember':state.remember=!state.remember;b.setAttribute('aria-checked',state.remember);b.parentElement.nextElementSibling.textContent=storageHelp();break;case'connect':state.connected=true;state.status='normal';state.connectionNotice=false;if(state.pendingInsight){state.pendingInsight=false;navigate('insight')}else{render()}toast('연결 완료 · 모의 동작');break;case'disconnect':state.connected=false;state.status='disconnected';state.remember=false;render();toast('연결과 저장 정보 삭제 완료 · 모의 동작');break;case'demo-setting':toast('설정 위치를 확인하는 시안입니다.');break;case'clear-cache':toast('캐시 삭제 동작 예시입니다. 저장된 캐시가 없는 시안입니다.');break;}});
app.addEventListener('scroll',()=>{if(state.screen!=='insight')return;let current=ids[0];for(const id of ids){const el=document.getElementById(id);if(el&&el.getBoundingClientRect().top-app.getBoundingClientRect().top<110)current=id;}device.querySelectorAll('[data-anchor]').forEach(b=>b.classList.toggle('active',b.dataset.anchor===current));},{passive:true});
document.querySelector('#screen').onchange=e=>{if(e.target.value==='insight'){enterInsight();return}state.pendingInsight=false;state.connectionNotice=false;state.settingsReturn='settings';navigate(e.target.value)};
document.querySelector('#state').onchange=e=>{state.status=e.target.value;state.connected=!['expired','disconnected'].includes(state.status);render();app.scrollTop=0};
document.querySelector('#theme').onclick=e=>{const light=device.dataset.theme==='dark';device.dataset.theme=light?'light':'dark';e.target.textContent=light?'다크 모드 보기':'라이트 모드 보기';if(state.screen==='settings')render()};
document.querySelector('#overview').onclick=e=>{const on=document.body.classList.toggle('overview');e.target.setAttribute('aria-pressed',on);e.target.textContent=on?'휴대폰 화면으로 보기':'전체 화면 길이로 보기'};
render();

if(new URLSearchParams(location.search).get('phone')==='1'){document.body.classList.add('phone-only');}
